tasks:
  daily:
    days-ahead: 7
    templates:
      - title: "Уборка (утро)"
        description: "Ежедневная утренняя уборка помещения"

      - title: "Прием пищи (завтрак)"
        description: "Подача и помощь в приеме завтрака"

      - title: "Прогулка"
        description: "Сопровождение на прогулку"

      - title: "Прием пищи (обед)"
        description: "Подача и помощь в приеме обеда"

      - title: "Прием пищи (ужин)"
        description: "Подача и помощь в приеме ужина"

      - title: "Уборка (вечер)"
        description: "Ежедневная вечерняя уборка помещения"