spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-pension
    username: postgres
    password: JustForFan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

cors:
  allowed-origins: http://localhost:5500,http://127.0.0.1:5500
  allow-credentials: true

jwt:
  secret: mySecretKey!mySecretKey!mySecretKey!mySecretKey!
  expiration: 10800000

logging:
  level:
    ru.eltech: DEBUG
    org.springframework.security: DEBUG

management.endpoints.web.exposure.include: health,info
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.endpoints.web.exposure.exclude: env,beans
