spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-pension
    username: postgres
    password: JustForFan
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

cors:
  allowed-origins: http://localhost:5500,http://127.0.0.1:5500

jwt:
  secret: mySecretKey!mySecretKey!mySecretKey!mySecretKey!
  expiration: 10800000